### ISSUE TITLE
Run as " 1 Generate Xtext Artifacts "

### ISSUE THREAD

**Issue by Eddie143code** [Epistimis/UDDL#29]
I followed the installation instructions as closely as possible and tried the installation 3 times.
I may have made a mistake but seem to be stuck at trying to run the Uddl.xtext file as " 1 Generate Xtext Artifacts ". 

Please find attached the error log file

[eclipse-workspace.log](https://github.com/Epistimis/UDDL/files/10730926/eclipse-workspace.log)

**Comment by steve-hickman-epistimis** [comment]
1. Set the HOME environment variable.  I don't know if that will fix it, but it can't hurt.
2. I will work through the instructions on a Windows machine and see if I can detect the problem.  Will take several hours.

**Comment by steve-hickman-epistimis** [comment]
See also this: https://stackoverflow.com/questions/42354891/synchronize-gradle-projects-with-workspace-failed . 
It might help.

You can also try this:
![Screenshot 2023-02-14 at 5 54 33 AM](https://user-images.githubusercontent.com/120406738/218758712-ebe7c0bc-2532-4d2f-9f4b-c011bca2a946.png)

Right click on the com.epistimis.uddl project. When the context menu comes up, select Gradle -> Refresh Gradle Project . And then retry.  It's just a guess but it might help.

**Comment by steve-hickman-epistimis** [comment]
Try this:
https://stackoverflow.com/questions/59131867/jre-system-library-is-always-unbound-in-eclipse-an-internal-error-occurred-dur/59251711#59251711

There are several possible solutions. Try them until one works

**Comment by steve-hickman-epistimis** [comment]
I've updated the Getting Started page with some additional steps (Installing Java and Gradle). See if that solves your problem.

**Comment by Eddie143code** [comment]
I updated buildship gradle then restarted eclipse. After this I reinstalled it and restarted eclipse again.

This fixed my issue.

Thank you for your time.
