### ISSUE TITLE
Unable to format the UDDL_SDM_Min.uddl file

### ISSUE THREAD

**Issue by Thomcray** [Epistimis/UDDL#34]
**Unable to format the file /com.epistimis.uddl.tests/src/com/epistimis/uddl/tests/UDDL_SDM_Min.uddl**.<br>

After running a new Eclipse and creating a new project with the UDDL_SDM_Min.uddl file in it, the text appears grey, and thus cannot be formatted.

**Comment by steve-hickman-epistimis** [comment]
@steve-hickman-epistimis
 
Member
[steve-hickman-epistimis](https://github.com/steve-hickman-epistimis) commented [1 hour ago](https://github.com/Epistimis/UDDL/issues/34#issuecomment-1435999836)
I can see by the number of files changed that you were able to generate XText artifacts. However, the UDDL file should not have been greyed out. Do this:

close the second Eclipse
In the first Eclipse, to a Project -> Clean / Rebuild All.
Check the Problem pane to make sure there are no Errors (Warnings and Infos are expected). If there are any Errors, attach a screenshot to this Issue showing the errors.
If there are no errors, start a second Eclipse and create a new Project. It should be an empty project (not a Java Project) in a new location (not in the same directory where the original UDDL file is). Then copy the UDDL file into the new project (don't link to it).
Open the new UDDL file. Eclipse should ask of you want to convert this to an XText project. Say yes.
If the UDDL file is editable and you have an Outline that shows the structure of the UDDL file content, then you're good to go. If the UDDL file in the new project is greyed out, then save the Console log from the first Eclipse and attach it to this Issue so I can diagnose the problem.

**Comment by Thomcray** [comment]
**I did as you instructed and got the following errors and warnings in the screenshots attached**.

![Screenshot (83)](https://user-images.githubusercontent.com/68615268/219974652-b6564778-5755-403d-ac4d-c588838c3aef.png)
![Screenshot (84)](https://user-images.githubusercontent.com/68615268/219974655-557a5925-e408-4800-9c79-b145d27c3fec.png)
![Screenshot (85)](https://user-images.githubusercontent.com/68615268/219974658-c101ca72-3bac-4519-91f3-ffb1c00183dd.png)
![Screenshot (86)](https://user-images.githubusercontent.com/68615268/219974660-479b737a-de2f-44ef-9bfa-1b9611a27186.png)
![Screenshot (87)](https://user-images.githubusercontent.com/68615268/219974663-af9a57d9-3ee3-4d67-901e-69d3e01c409a.png)
![Screenshot (88)](https://user-images.githubusercontent.com/68615268/219974664-c54e50bf-c59f-4dca-af10-747bea7c0406.png)

**Comment by steve-hickman-epistimis** [comment]
The warnings don't matter. The only thing that matters are the errors. In this case, the errors that matter are the ones in the MANIFEST.MF files. These exist because Eclipse can't find the relevant projects. You should be able to fix this by:

Right mouse -> Properties ‘Java Build Path’ - Select ‘Classpath’ and click ‘Add’ the select the project with the unresolved reference.
